version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
  django:
    container_name: django
    env_file:
      - backend/.env.docker
    build: backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - media:/media
  react:
    container_name: react
    build: frontend/apps/web
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - django
volumes:
  postgres-data:
  media: